// Code generated by tools/gen_tables.ps1; DO NOT EDIT.
// Source: X32-Behringer by Patrick-Gilles Maillot (GPLv3) - X32.c v0.88 and the
// command table headers. https://github.com/pmaillot/X32-Behringer

package x32

// Type is the OSC value/command type of a table entry (parity with "enum types" in X32.c).
type Type uint8

const (
	TNIL       Type = 0
	TI32       Type = 1
	TF32       Type = 2
	TS32       Type = 3
	TB32       Type = 4
	TE32       Type = 5
	TP32       Type = 6
	TRES2      Type = 7
	TRES3      Type = 8
	TRES4      Type = 9
	TFX32      Type = 10
	TOFFON     Type = 11
	TCMONO     Type = 12
	TCSOLO     Type = 13
	TCTALK     Type = 14
	TCTALKAB   Type = 15
	TCOSC      Type = 16
	TCROUTSW   Type = 17
	TCROUTIN   Type = 18
	TCROUTAC   Type = 19
	TCROUTOT   Type = 20
	TCROUTPLAY Type = 21
	TCCTRL     Type = 22
	TCENC      Type = 23
	TCTAPE     Type = 24
	TCMIX      Type = 25
	TCHCO      Type = 26
	TCHDE      Type = 27
	TCHPR      Type = 28
	TCHGA      Type = 29
	TCHGF      Type = 30
	TCHDY      Type = 31
	TCHDF      Type = 32
	TCHIN      Type = 33
	TCHEQ      Type = 34
	TCHMX      Type = 35
	TCHMO      Type = 36
	TCHME      Type = 37
	TCHGRP     Type = 38
	TCHAMIX    Type = 39
	TAXPR      Type = 40
	TBSCO      Type = 41
	TMXPR      Type = 42
	TMXDY      Type = 43
	TMSMX      Type = 44
	TFXTYP1    Type = 45
	TFXSRC     Type = 46
	TFXPAR1    Type = 47
	TFXTYP2    Type = 48
	TFXPAR2    Type = 49
	TOMAIN     Type = 50
	TOMAIN2    Type = 51
	TOP16      Type = 52
	TOMAIND    Type = 53
	THAMP      Type = 54
	TPREFS     Type = 55
	TPIR       Type = 56
	TPIQ       Type = 57
	TPCARD     Type = 58
	TPRTA      Type = 59
	TPIP       Type = 60
	TPADDR     Type = 61
	TPMASK     Type = 62
	TPGWAY     Type = 63
	TSTAT      Type = 64
	TSSCREEN   Type = 65
	TSCHA      Type = 66
	TSMET      Type = 67
	TSROU      Type = 68
	TSSET      Type = 69
	TSLIB      Type = 70
	TSFX       Type = 71
	TSMON      Type = 72
	TSUSB      Type = 73
	TSSCE      Type = 74
	TSASS      Type = 75
	TSSOLOSW   Type = 76
	TSAES      Type = 77
	TSTAPE     Type = 78
	TSOSC      Type = 79
	TSTALK     Type = 80
	TUSB       Type = 81
	TSNAM      Type = 82
	TSCUE      Type = 83
	TSSCN      Type = 84
	TSSNP      Type = 85
	THA        Type = 86
	TACTION    Type = 87
	TUREC      Type = 88
	TSLIBS     Type = 89
	TD48       Type = 90
	TD48A      Type = 91
	TD48G      Type = 92
	TUROUO     Type = 93
	TUROUI     Type = 94
	TPKEY      Type = 95
)

var typeNames = map[Type]string{
	TNIL:       "NIL",
	TI32:       "I32",
	TF32:       "F32",
	TS32:       "S32",
	TB32:       "B32",
	TE32:       "E32",
	TP32:       "P32",
	TRES2:      "RES2",
	TRES3:      "RES3",
	TRES4:      "RES4",
	TFX32:      "FX32",
	TOFFON:     "OFFON",
	TCMONO:     "CMONO",
	TCSOLO:     "CSOLO",
	TCTALK:     "CTALK",
	TCTALKAB:   "CTALKAB",
	TCOSC:      "COSC",
	TCROUTSW:   "CROUTSW",
	TCROUTIN:   "CROUTIN",
	TCROUTAC:   "CROUTAC",
	TCROUTOT:   "CROUTOT",
	TCROUTPLAY: "CROUTPLAY",
	TCCTRL:     "CCTRL",
	TCENC:      "CENC",
	TCTAPE:     "CTAPE",
	TCMIX:      "CMIX",
	TCHCO:      "CHCO",
	TCHDE:      "CHDE",
	TCHPR:      "CHPR",
	TCHGA:      "CHGA",
	TCHGF:      "CHGF",
	TCHDY:      "CHDY",
	TCHDF:      "CHDF",
	TCHIN:      "CHIN",
	TCHEQ:      "CHEQ",
	TCHMX:      "CHMX",
	TCHMO:      "CHMO",
	TCHME:      "CHME",
	TCHGRP:     "CHGRP",
	TCHAMIX:    "CHAMIX",
	TAXPR:      "AXPR",
	TBSCO:      "BSCO",
	TMXPR:      "MXPR",
	TMXDY:      "MXDY",
	TMSMX:      "MSMX",
	TFXTYP1:    "FXTYP1",
	TFXSRC:     "FXSRC",
	TFXPAR1:    "FXPAR1",
	TFXTYP2:    "FXTYP2",
	TFXPAR2:    "FXPAR2",
	TOMAIN:     "OMAIN",
	TOMAIN2:    "OMAIN2",
	TOP16:      "OP16",
	TOMAIND:    "OMAIND",
	THAMP:      "HAMP",
	TPREFS:     "PREFS",
	TPIR:       "PIR",
	TPIQ:       "PIQ",
	TPCARD:     "PCARD",
	TPRTA:      "PRTA",
	TPIP:       "PIP",
	TPADDR:     "PADDR",
	TPMASK:     "PMASK",
	TPGWAY:     "PGWAY",
	TSTAT:      "STAT",
	TSSCREEN:   "SSCREEN",
	TSCHA:      "SCHA",
	TSMET:      "SMET",
	TSROU:      "SROU",
	TSSET:      "SSET",
	TSLIB:      "SLIB",
	TSFX:       "SFX",
	TSMON:      "SMON",
	TSUSB:      "SUSB",
	TSSCE:      "SSCE",
	TSASS:      "SASS",
	TSSOLOSW:   "SSOLOSW",
	TSAES:      "SAES",
	TSTAPE:     "STAPE",
	TSOSC:      "SOSC",
	TSTALK:     "STALK",
	TUSB:       "USB",
	TSNAM:      "SNAM",
	TSCUE:      "SCUE",
	TSSCN:      "SSCN",
	TSSNP:      "SSNP",
	THA:        "HA",
	TACTION:    "ACTION",
	TUREC:      "UREC",
	TSLIBS:     "SLIBS",
	TD48:       "D48",
	TD48A:      "D48A",
	TD48G:      "D48G",
	TUROUO:     "UROUO",
	TUROUI:     "UROUI",
	TPKEY:      "PKEY",
}

// String returns the C name of a type (for dumping / debugging).
func (t Type) String() string {
	if s, ok := typeNames[t]; ok {
		return s
	}
	return "UNKNOWN"
}
